modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "beings_of_elderia"
version = "${version}"
displayName = "Beings of Elderia"
authors = "lwkysad, kyber-6"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.beings_of_elderia]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beings_of_elderia]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beings_of_elderia]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.beings_of_elderia]]
modId = "azurelib"
mandatory = true
versionRange = "[2.0.30,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beings_of_elderia]]
modId = "smartbrainlib"
mandatory = true
versionRange = "[1.14.2,)"
ordering = "NONE"
side = "BOTH"

